Adding CoreRP test suite (#2690)
* Adding WIP coreRP test suite

* Wake up CI

* [TEMP] add validate-bicep back

* test

* Fixing extra tag in azure pipeline

* [TEMP] removing ci for appcore

* Using CLI commands instead of cluster proxy

* Changing resource group for tests to default

* Removing bicep validation

* Fixing linting issue

* Moving rad bicep download feature flag

* enabling nested modules test

* Removing parallel testing for corerp

* Updating tests to use rad deploy and application clients

* Updating corerp test

* Create resource group for deployments

* slash

* Long day lol

Co-authored-by: Will Smith <willsmith@microsoft.com>
Co-authored-by: Justin Kotalik <jukotali@microsoft.com>

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -65,6 +65,61 @@ stages:
 - stage: FunctionalTest
   dependsOn: ImageBuild
   jobs:
+  - job: ApplicationsCoreRP
+    pool:
+      vmImage: 'ubuntu-latest'
+    steps:
+    - task: GoTool@0
+      inputs:
+        version: '1.18'
+    - script: |
+        echo "##vso[task.setvariable variable=goBuildCache;isOutput=true]$(go env GOCACHE)"
+      displayName: Set Go cache paths
+      name: gocachepath
+    - task: Cache@2
+      inputs:
+        key: 'go | "$(Agent.OS)" | go.mod'
+        restoreKeys: | 
+          go | "$(Agent.OS)"
+        path: $(gocachepath.goBuildCache)
+      displayName: Cache GO packages
+    - script: |
+        echo channel: $REL_CHANNEL, version: $REL_VERSION
+        make build
+        cp ./dist/linux_amd64/release/rad ./dist/
+        chmod +x ./dist/rad
+      displayName: Build and copy rad exe
+    - script: |
+        export PATH=$(Build.SourcesDirectory)/dist:$PATH
+        cd $(Build.SourcesDirectory)
+        which rad || { echo "cannot find rad"; exit 1; }
+        export RAD_FF_ENABLE_BICEP_EXTENSIBILITY=true
+        rad bicep download
+      displayName: rad bicep download
+    - script: | 
+        mkdir -p kind/
+        curl -sSLo "kind/kind" "https://github.com/kubernetes-sigs/kind/releases/download/v0.11.0/kind-linux-amd64"
+        chmod +x "kind/kind"
+        kind create cluster --name radius --wait 60s
+    - script: |
+        export PATH=$(Build.SourcesDirectory)/dist:$PATH
+        mkdir ~/.rad
+        export RAD_FF_ENABLE_UCP=true
+        dist/rad env install kubernetes --chart ${{ variables.RADIUS_CHART_LOCATION }} --image ${{ variables.DOCKER_REGISTRY }}/radius-rp --tag ${{ variables.REL_VERSION }} --appcore-image ${{ variables.DOCKER_REGISTRY }}/appcore-rp --appcore-tag ${{ variables.REL_VERSION }}  --ucp-image ${{ variables.DOCKER_REGISTRY }}/ucpd --ucp-tag ${{ variables.REL_VERSION }}
+      displayName: rad env install kubernetes
+    - script: |
+        kubectl get pods -n radius-system
+        kubectl describe pods -n radius-system
+      condition: always()
+      continueOnError: 'true'
+    - script: |
+        export PATH=$(Build.SourcesDirectory)/dist:$PATH
+        export TEST_TIMEOUT=${{ variables.K8S_FUNCTIONALTEST_TIMEOUT }}
+        export RADIUS_CONTAINER_LOG_PATH=$(Build.SourcesDirectory)/${{ variables.RADIUS_CONTAINER_LOG_BASE }}
+        make test-functional-corerp
+    - publish: $(Build.SourcesDirectory)/dist/container_logs
+      displayName: Publish container logs
+      condition: always()
   - job: Kubernetes
     pool:
       vmImage: 'ubuntu-latest'
