Moving rad bicep download feature flag

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -85,11 +85,17 @@ stages:
       displayName: Cache GO packages
     - script: |
         echo channel: $REL_CHANNEL, version: $REL_VERSION
-        export RAD_FF_ENABLE_BICEP_EXTENSIBILITY=true
         make build
         cp ./dist/linux_amd64/release/rad ./dist/
         chmod +x ./dist/rad
       displayName: Build and copy rad exe
+    - script: |
+        export PATH=$(Build.SourcesDirectory)/dist:$PATH
+        cd $(Build.SourcesDirectory)
+        which rad || { echo "cannot find rad"; exit 1; }
+        export RAD_FF_ENABLE_BICEP_EXTENSIBILITY=true
+        rad bicep download
+      displayName: rad bicep download
     - script: | 
         mkdir -p kind/
         curl -sSLo "kind/kind" "https://github.com/kubernetes-sigs/kind/releases/download/v0.11.0/kind-linux-amd64"
@@ -106,12 +112,6 @@ stages:
         kubectl describe pods -n radius-system
       condition: always()
       continueOnError: 'true'
-    - script: |
-        export PATH=$(Build.SourcesDirectory)/dist:$PATH
-        cd $(Build.SourcesDirectory)
-        which rad || { echo "cannot find rad"; exit 1; }
-        rad bicep download
-      displayName: rad bicep download
     - script: |
         export PATH=$(Build.SourcesDirectory)/dist:$PATH
         export TEST_TIMEOUT=${{ variables.K8S_FUNCTIONALTEST_TIMEOUT }}
