update the pipeline

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -47,7 +47,7 @@ stages:
     - task: Cache@2
       inputs:
         key: 'go | "$(Agent.OS)" | go.mod'
-        restoreKeys: | 
+        restoreKeys: |
           go | "$(Agent.OS)"
         path: $(gocachepath.goBuildCache)
       displayName: Cache GO packages
@@ -62,23 +62,95 @@ stages:
       displayName: publish container
 
 - stage: FunctionalTest
-  # dependsOn: ImageBuild
+  dependsOn: ImageBuild
   jobs:
   - job: ApplicationsCoreRP
     pool:
       vmImage: 'ubuntu-latest'
     steps:
+    - task: GoTool@0
+      inputs:
+        version: '1.18'
+    - script: |
+        echo "##vso[task.setvariable variable=goBuildCache;isOutput=true]$(go env GOCACHE)"
+      displayName: Set Go cache paths
+      name: gocachepath
+    - task: Cache@2
+      inputs:
+        key: 'go | "$(Agent.OS)" | go.mod'
+        restoreKeys: |
+          go | "$(Agent.OS)"
+        path: $(gocachepath.goBuildCache)
+      displayName: Cache GO packages
+    - script: |
+        echo channel: $REL_CHANNEL, version: $REL_VERSION
+        make build
+        cp ./dist/linux_amd64/release/rad ./dist/
+        chmod +x ./dist/rad
+      displayName: Build and copy rad exe
+    - script: |
+        export PATH=$(Build.SourcesDirectory)/dist:$PATH
+        cd $(Build.SourcesDirectory)
+        which rad || { echo "cannot find rad"; exit 1; }
+        rad bicep download
+      displayName: rad bicep download
+    - script: |
+        mkdir -p kind/
+        curl -sSLo "kind/kind" "https://github.com/kubernetes-sigs/kind/releases/download/v0.11.0/kind-linux-amd64"
+        chmod +x "kind/kind"
+        kind create cluster --name radius --wait 60s
+      displayName: create kind cluster
+    - script: |
+        az login --service-principal \
+          --username $(INTEGRATION_TEST_SP_APP_ID) \
+          --password $(INTEGRATION_TEST_SP_PASSWORD) \
+          --tenant $(INTEGRATION_TEST_TENANT_ID)
+      displayName: az CLI login
+    - script: |
+        echo "##vso[task.setvariable variable=INTEGRATION_TEST_RESOURCE_GROUP_NAME]radius-$(date +%s%N)"
+      displayName: Define a resource group name
+    - script: az account set --subscription ${{ variables.INTEGRATION_TEST_SUBSCRIPTION_ID }}
+      displayName: az account set
+    - script: |
+        export RANID=$(date +%s%N)
+        arr=("eastasia")
+        index=$(expr $RANID % 1)
+        export LOCATION=${arr[$index]}
+        az group create \
+          --location $LOCATION \
+          --name $(INTEGRATION_TEST_RESOURCE_GROUP_NAME) \
+          --subscription ${{ variables.INTEGRATION_TEST_SUBSCRIPTION_ID }}
+        while [ $(az group exists --name $(INTEGRATION_TEST_RESOURCE_GROUP_NAME)) = false ]; do sleep 2; done
+      displayName: Create the resource group
+    - script: |
+        export PATH=$(Build.SourcesDirectory)/dist:$PATH
+        mkdir ~/.rad
+        dist/rad env init kubernetes \
+          --chart ${{ variables.RADIUS_CHART_LOCATION }} \
+          --tag ${{ variables.REL_VERSION }} --appcore-image ${{ variables.DOCKER_REGISTRY }}/appcore-rp \
+          --appcore-tag ${{ variables.REL_VERSION }}  --ucp-image ${{ variables.DOCKER_REGISTRY }}/ucpd \
+          --ucp-tag ${{ variables.REL_VERSION }} \
+          --provider-azure \
+          --provider-azure-resource-group $INTEGRATION_TEST_RESOURCE_GROUP_NAME \
+          --provider-azure-client-id $INTEGRATION_TEST_SP_APP_ID \
+          --provider-azure-client-secret $INTEGRATION_TEST_SP_PASSWORD \
+          --provider-azure-tenant-id $INTEGRATION_TEST_TENANT_ID \
+          --provider-azure-subscription ${{ variables.INTEGRATION_TEST_SUBSCRIPTION_ID }} \
+      env:
+        INTEGRATION_TEST_SP_APP_ID: $(INTEGRATION_TEST_SP_APP_ID)
+        INTEGRATION_TEST_TENANT_ID: $(INTEGRATION_TEST_TENANT_ID)
+        INTEGRATION_TEST_SP_PASSWORD: $(INTEGRATION_TEST_SP_PASSWORD)
+      displayName: rad env init kubernetes
+    - script: |
+        kubectl get pods -n radius-system
+        kubectl describe pods -n radius-system
+        kubectl create secret generic mysecret --from-literal=mysecret=mysecret
+      condition: always()
+      continueOnError: 'true'
     - script: |
         export PATH=$(Build.SourcesDirectory)/dist:$PATH
         export TEST_TIMEOUT=${{ variables.K8S_FUNCTIONALTEST_TIMEOUT }}
         export RADIUS_CONTAINER_LOG_PATH=$(Build.SourcesDirectory)/${{ variables.RADIUS_CONTAINER_LOG_BASE }}/corerptest
-        echo "loc 155 $(MSSQL_RESOURCE_ID)" > test.txt
-        echo "loc 156 $MSSQL_RESOURCE_ID" >> test.txt
-        export REDIS_RESOURCE_ID=$REDIS_RESOURCE_ID
-        echo "loc 158 $REDIS_RESOURCE_ID" >> test.txt
-        export REDIS_RESOURCE_ID=$(REDIS_RESOURCE_ID)
-        echo "loc 80 $REDIS_RESOURCE_ID" >> test.txt
-        cat test.txt
         make test-functional-corerp
       env:
         MONGODB_RESOURCE_ID: $(MONGODB_RESOURCE_ID)
@@ -97,7 +169,10 @@ stages:
       displayName: run functional ucp tests
     - publish: $(Build.SourcesDirectory)/dist/container_logs
       displayName: Publish container logs
+<<<<<<< HEAD
       artifact: FunctionalTest.ApplicationsCoreRPLogs.$(Build.BuildNumber)
+=======
+>>>>>>> 6b5c8b2d (update the pipeline)
       condition: always()
     - script: |
         az group delete \
