simplify

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -157,12 +157,11 @@ jobs:
 
             > The coverage result does not include the functional test coverage. 
       - name: Stop build if PR branch coverage is lower than main branch.
-        if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux' && github.event.pull_request
+        if: ${{ steps.gen-coverage.outputs.lower_coverage }} == 'true' &&  matrix.target_arch == 'amd64' && matrix.target_os == 'linux' && github.event.pull_request
         run: |
-          if [ "${{ steps.gen-coverage.outputs.lower_coverage }}" = "true" ]; then
-            exit 1
-          fi
-          exit 0
+          echo "coverage is down from ${{ env.main_coverage }} % to ${{ env.ut_coverage }} %"
+          echo "failed to merge"
+          exit 1
       - name: Save coverage (only main push)
         uses: actions/cache/save@v3
         if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux' && github.ref == 'refs/heads/main'
