Add support for 'local dev' environment
This change introduces a 'local dev' environment concept for `rad` to
manage. Really this is just another variant of Kubernetes, what makes it
special is that we're curating the experience and providing some
lifecycle management inside `rad`.

The 'hard parts' of using Kubernetes as a local dev environment are
related to all of the choices on needs to make that are outside of the
scope of Radius:

- What ingress controller and how to set it up
- Where do I push my docker images (local registry)
- Understanding and accomodating behavior differences in networking

If we manage the lifecycle of the cluster then we can provide a curated
experience for all of these needs and leave less for the user to do.

The new functionality here includes:

- Creating/destroying the K3d cluster
- Starting/stopping the K3d cluster
- Reporting status
- Installing our bits with the correct configuration

This first cut won't include deploying any applications, just the
infrastructure management. There are a few small issues to fix blocking
those scenarios that will be done separately.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -252,7 +252,7 @@ jobs:
       run: |
         export PATH=$GITHUB_WORKSPACE/dist:$PATH
         mkdir ~/.rad
-        dist/rad env init kubernetes -c ${{ env.RADIUS_CHART_LOCATION }} --image ${{ env.DOCKER_REGISTRY }}/radius-controller --tag ${{ env.REL_VERSION }}
+        dist/rad env init kubernetes --chart ${{ env.RADIUS_CHART_LOCATION }} --image ${{ env.DOCKER_REGISTRY }}/radius-controller --tag ${{ env.REL_VERSION }}
         # Print config for sanity check
         cat ~/.rad/config.yaml
     - name: Download Bicep
@@ -273,6 +273,74 @@ jobs:
       with:
         name: container_logs
         path: ./${{ env.RADIUS_CONTAINER_LOG_BASE }}
+  
+  local_dev_tests:
+    name: Run Local Dev tests
+    needs: [ 'build', 'images', 'pre_check' ]
+    if: ${{ startsWith(github.ref, 'refs/pull/') && needs.pre_check.outputs.should_skip != 'true' }} # run on PR
+    runs-on: ubuntu-latest
+    env:
+      GOVER: '^1.17'
+      DOCKER_REGISTRY: radius.azurecr.io
+      # Timeout used for functional tests
+      LOCALDEV_FUNCTIONALTEST_TIMEOUT: 20m
+      RADIUS_CONTAINER_LOG_BASE: dist/container_logs
+      RADIUS_CHART_LOCATION: deploy/Chart/
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: Set up Go ${{ env.GOVER }}
+      uses: actions/setup-go@v2
+      with:
+        go-version: ${{ env.GOVER }}
+    - name: Parse release version and set environment variables
+      run: python ./.github/scripts/get_release_version.py
+    - name: Download release artifacts
+      uses: actions/download-artifact@v2
+      with:
+        name: rad_cli_linux_amd64
+        path: dist
+    - name: Make rad executable
+      run: chmod +x rad
+      working-directory: dist
+    - name: Install k3d
+      run: curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
+    - name: Run 'rad env init dev'
+      run: |
+        export PATH=$GITHUB_WORKSPACE/dist:$PATH
+        mkdir ~/.rad
+        dist/rad env init dev --name dev --chart ${{ env.RADIUS_CHART_LOCATION }} --image ${{ env.DOCKER_REGISTRY }}/radius-controller --tag ${{ env.REL_VERSION }}
+        # Print config for sanity check
+        cat ~/.rad/config.yaml
+    - name: Dapr tool installer
+      uses: dapr/setup-dapr@v1
+    - name: Install dapr into cluster
+      run: dapr init -k --wait --timeout 600
+    - name: Download Bicep
+      run: |
+        export PATH=$GITHUB_WORKSPACE/dist:$PATH
+        cd $GITHUB_WORKSPACE
+        which rad || { echo "cannot find rad"; exit 1; }
+        rad bicep download
+    - name: Run Local Dev tests (PR)
+      run: |
+        export PATH=$GITHUB_WORKSPACE/dist:$PATH
+        export TEST_TIMEOUT=${{ env.LOCALDEV_FUNCTIONALTEST_TIMEOUT }}
+        export RADIUS_CONTAINER_LOG_PATH=$GITHUB_WORKSPACE/${{ env.RADIUS_CONTAINER_LOG_BASE }}
+        make test-functional-localdev
+    - name: Run 'rad env delete'
+      run: |
+        export PATH=$GITHUB_WORKSPACE/dist:$PATH
+        dist/rad env delete dev --yes
+        # Print config for sanity check
+        cat ~/.rad/config.yaml
+    - name: Upload container logs
+      if: always()
+      uses: actions/upload-artifact@master
+      with:
+        name: container_logs
+        path: ./${{ env.RADIUS_CONTAINER_LOG_BASE }}
+
   deploy_tests:
     name: Run deployment tests
     needs: [ 'build', 'images', 'pre_check' ]
