script-test
Signed-off-by: Young Bu Park <youngp@microsoft.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -64,8 +64,42 @@ env:
 
   # URL to get source code for building the image
   IMAGE_SRC: https://github.com/radius-project/radius
+  ISSUE_CREATE_THRESHOLD: 2
 
 jobs:
+  report-failure:
+    name: Report test failure
+    runs-on: ubuntu-latest
+    steps:
+      - name: Count recently failed tests
+        id: count_failures
+        uses: actions/github-script@v7
+        with:
+          script: |
+            response = await github.rest.actions.listWorkflowRuns({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              workflow_id: 'long-running-azure.yaml',
+              event: 'schedule',
+              per_page: 10
+            });
+            
+            failureCount = 1;
+            for (const run of response.data.workflow_runs) {
+              if (run.conclusion === 'failure') {
+                failureCount++;
+              } else {
+                break;
+              }
+            }
+            console.log(`Found ${failureCount} failed runs`);
+            return failureCount;
+      - name: Create failure issue for failing long running test run
+        # Only create an issue if there are (env.ISSUE_CREATE_THRESHOLD) failures of the recent tests.
+        if: steps.count_failures.outputs.result >= env.ISSUE_CREATE_THRESHOLD
+        run: |
+            echo "hello"
+            exit 1
   build-and-push-cli:
     name: Build ${{ matrix.target_os }}_${{ matrix.target_arch }} binaries
     runs-on: ubuntu-latest
