workflows
Signed-off-by: willdavsmith <willdavsmith@gmail.com>

diff --git a/.github/workflows/functional-test-noncloud.yaml b/.github/workflows/functional-test-noncloud.yaml
--- a/.github/workflows/functional-test-noncloud.yaml
+++ b/.github/workflows/functional-test-noncloud.yaml
@@ -381,6 +381,20 @@ jobs:
           git-username: ${{ env.GIT_HTTP_USERNAME }}
           git-password: ${{ secrets.GITEA_PASSWORD }}
 
+      - name: Port-forward to Git server
+        if: matrix.name == 'kubernetes-noncloud'
+        run: |
+          # Start port forwarding in the background
+          kubectl port-forward -n git-http-backend svc/git-http 30080:3000 &
+
+          # Wait for port forwarding to be established
+          sleep 5
+
+          # Test the connection to ensure port forwarding is working
+          curl -s http://localhost:30080 > /dev/null || (echo "Port forwarding failed" && exit 1)
+
+          echo "Port forwarding established successfully"
+
       - name: Install Dapr CLI and control plane
         if: matrix.name == 'daprrp-noncloud'
         run: |
diff --git a/.github/workflows/long-running-azure.yaml b/.github/workflows/long-running-azure.yaml
--- a/.github/workflows/long-running-azure.yaml
+++ b/.github/workflows/long-running-azure.yaml
@@ -554,22 +554,23 @@ jobs:
           echo ":x: Failed to install Radius for functional test." >> $GITHUB_STEP_SUMMARY
       - name: Install Flux CLI and Source Controller
         uses: ./.github/actions/install-flux
-      # - name: Install Git HTTP backend
-      #   uses: ./.github/actions/install-git-http-backend
-      #   with:
-      #     git-username: ${{ env.GIT_HTTP_USERNAME }}
-      #     git-password: ${{ secrets.GITEA_PASSWORD }}
-      # - name: Port-forward to Git server
-      #   run: |
-      #     kubectl port-forward -n git-http-backend svc/git-http 30080:3000 &
-          
-      #     # Wait for port forwarding to be established
-      #     sleep 5
-          
-      #     # Test the connection to ensure port forwarding is working
-      #     curl -s http://localhost:30080 > /dev/null || (echo "Port forwarding failed" && exit 1)
-          
-      #     echo "Port forwarding established successfully"
+      - name: Install Git HTTP backend
+        uses: ./.github/actions/install-git-http-backend
+        with:
+          git-username: ${{ env.GIT_HTTP_USERNAME }}
+          git-password: ${{ secrets.GITEA_PASSWORD }}
+      - name: Port-forward to Git server
+        run: |
+          # Start port forwarding in the background
+          kubectl port-forward -n git-http-backend svc/git-http 30080:3000 &
+
+          # Wait for port forwarding to be established
+          sleep 5
+
+          # Test the connection to ensure port forwarding is working
+          curl -s http://localhost:30080 > /dev/null || (echo "Port forwarding failed" && exit 1)
+
+          echo "Port forwarding established successfully"
       - name: Publish Terraform test recipes
         run: |
           make publish-test-terraform-recipes
