Disable Gitea install and Flux tests
Signed-off-by: willdavsmith <willdavsmith@gmail.com>

diff --git a/.github/workflows/functional-test-noncloud.yaml b/.github/workflows/functional-test-noncloud.yaml
--- a/.github/workflows/functional-test-noncloud.yaml
+++ b/.github/workflows/functional-test-noncloud.yaml
@@ -374,30 +374,32 @@ jobs:
         if: matrix.name == 'kubernetes-noncloud'
         uses: ./.github/actions/install-flux
 
-      - name: Install Gitea
-        if: matrix.name == 'kubernetes-noncloud'
-        id: install-gitea
-        uses: ./.github/actions/install-gitea
-        env:
-          GITEA_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
-        with:
-          gitea-username: ${{ env.GITEA_USERNAME }}
-          gitea-email: ${{ env.GITEA_EMAIL }}
-          gitea-access-token-name: ${{ env.GITEA_ACCESS_TOKEN_NAME }}
+      # https://github.com/radius-project/radius/issues/10441
+      # - name: Install Gitea
+      #   if: matrix.name == 'kubernetes-noncloud'
+      #   id: install-gitea
+      #   uses: ./.github/actions/install-gitea
+      #   env:
+      #     GITEA_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
+      #   with:
+      #     gitea-username: ${{ env.GITEA_USERNAME }}
+      #     gitea-email: ${{ env.GITEA_EMAIL }}
+      #     gitea-access-token-name: ${{ env.GITEA_ACCESS_TOKEN_NAME }}
  
-      - name: Port-forward to Gitea
-        if: matrix.name == 'kubernetes-noncloud'
-        run: |
-          # Start port forwarding in the background
-          kubectl port-forward -n gitea svc/gitea-http 30080:3000 &
+      # https://github.com/radius-project/radius/issues/10441
+      # - name: Port-forward to Gitea
+      #   if: matrix.name == 'kubernetes-noncloud'
+      #   run: |
+      #     # Start port forwarding in the background
+      #     kubectl port-forward -n gitea svc/gitea-http 30080:3000 &
           
-          # Wait for port forwarding to be established
-          sleep 5
+      #     # Wait for port forwarding to be established
+      #     sleep 5
           
-          # Test the connection to ensure port forwarding is working
-          curl -s http://localhost:30080 > /dev/null || (echo "Port forwarding failed" && exit 1)
+      #     # Test the connection to ensure port forwarding is working
+      #     curl -s http://localhost:30080 > /dev/null || (echo "Port forwarding failed" && exit 1)
           
-          echo "Port forwarding established successfully"
+      #     echo "Port forwarding established successfully"
 
       - name: Install Dapr CLI and control plane
         if: matrix.name == 'daprrp-noncloud'
