Add functional test: UDT Phase 1 E2E Test (Original PR #8924) (#9073)
This is the same PR as Original PR :
(https://github.com/radius-project/radius/pull/8924)
This PR includes additional commit to original commit for LRT updates:
([8fdfd1d4d](https://github.com/radius-project/radius/pull/9073/commits/8fdfd1d4dd32902798658b153b258d317a5a282e))

This pull request adds or changes features of Radius and has an approved
issue (https://github.com/radius-project/radius/issues/6688)

Fixes: Part of #6688

Please verify that the PR meets the following requirements, where
applicable:

- An overview of proposed schema changes is included in a linked GitHub
issue.
    - [ ] Yes
    - [ ] Not applicable
- A design document PR is created in the [design-notes
repository](https://github.com/radius-project/design-notes/), if new
APIs are being introduced.
    - [ ] Yes
    - [ ] Not applicable
- The design document has been reviewed and approved by Radius
maintainers/approvers.
    - [ ] Yes
    - [ ] Not applicable
- A PR for the [samples
repository](https://github.com/radius-project/samples) is created, if
existing samples are affected by the changes in this PR.
    - [ ] Yes
    - [ ] Not applicable
- A PR for the [documentation
repository](https://github.com/radius-project/docs) is created, if the
changes in this PR affect the documentation or any user facing updates
are made.
    - [ ] Yes
    - [ ] Not applicable
- A PR for the [recipes
repository](https://github.com/radius-project/recipes) is created, if
existing recipes are affected by the changes in this PR.
    - [ ] Yes
    - [ ] Not applicable

---------

Signed-off-by: lakshmimsft <ljavadekar@microsoft.com>

diff --git a/.github/workflows/long-running-azure.yaml b/.github/workflows/long-running-azure.yaml
--- a/.github/workflows/long-running-azure.yaml
+++ b/.github/workflows/long-running-azure.yaml
@@ -302,18 +302,17 @@ jobs:
         with:
           path: ./dist/cache
           key: radius-test-latest-${{ github.sha }}-${{ github.run_number }}
-      - name: 'Login via Azure CLI'
-        uses: azure/login@v2
-        with:
-          client-id: ${{ secrets.BICEPTYPES_CLIENT_ID }}
-          tenant-id: ${{ secrets.BICEPTYPES_TENANT_ID }}
-          subscription-id: ${{ secrets.BICEPTYPES_SUBSCRIPTION_ID }}    
       - name: Publish UDT types
-        if: steps.skip-build.outputs.SKIP_BUILD != 'true'
         run: |
           mkdir ./bin
           cp ./dist/linux_amd64/release/rad ./bin/rad
           chmod +x ./bin/rad
+          export PATH=$GITHUB_WORKSPACE/bin:$PATH
+          which rad || { echo "cannot find rad"; exit 1; }
+          rad bicep publish-extension -f ./test/functional-portable/dynamicrp/noncloud/resources/testdata/usertypealpha.yaml --target br:${{ env.BICEP_TYPES_REGISTRY }}/testresources:latest" --force
+      - name: Publish Bicep Test Recipes
+        if: steps.skip-build.outputs.SKIP_BUILD != 'true'
+        run: |
           export PATH=$GITHUB_WORKSPACE/bin:$PATH
           which rad || { echo "cannot find rad"; exit 1; }
           rad bicep download
@@ -597,6 +596,8 @@ jobs:
           bicep restore ./test/functional-portable/corerp/cloud/resources/testdata/corerp-azure-connection-database-service.bicep --force
           # Restore AWS Bicep types 
           bicep restore ./test/functional-portable/corerp/cloud/resources/testdata/aws-s3-bucket.bicep --force
+          # Restore UDT Test Bicep types
+          bicep restore ./test/functional-portable/dynamicrp/noncloud/resources/testdata/usertypealpha-recipe.bicep
       - name: Run functional tests
         run: |
           # Ensure rad cli is in path before running tests.
