updating LRT to publish UDT types
Signed-off-by: lakshmimsft <ljavadekar@microsoft.com>

diff --git a/.github/workflows/long-running-azure.yaml b/.github/workflows/long-running-azure.yaml
--- a/.github/workflows/long-running-azure.yaml
+++ b/.github/workflows/long-running-azure.yaml
@@ -67,6 +67,8 @@ env:
   CONTAINER_REGISTRY: ghcr.io/radius-project/dev
   # Container registry for storing Bicep recipe artifacts
   BICEP_RECIPE_REGISTRY: ghcr.io/radius-project/dev
+  # bicep-types ACR url for uploading UDT Bicep types
+  BICEP_TYPES_REGISTRY: 'biceptypes.azurecr.io'
   # The radius functional test timeout
   FUNCTIONALTEST_TIMEOUT: 60m
   # The Azure Location to store test resources
@@ -300,12 +302,17 @@ jobs:
         with:
           path: ./dist/cache
           key: radius-test-latest-${{ github.sha }}-${{ github.run_number }}
-      - name: Publish Bicep Test Recipes
-        if: steps.skip-build.outputs.SKIP_BUILD != 'true'
+      - name: Publish UDT types
         run: |
           mkdir ./bin
           cp ./dist/linux_amd64/release/rad ./bin/rad
           chmod +x ./bin/rad
+          export PATH=$GITHUB_WORKSPACE/bin:$PATH
+          which rad || { echo "cannot find rad"; exit 1; }
+          rad bicep publish-extension -f ./test/functional-portable/dynamicrp/noncloud/resources/testdata/usertypealpha.yaml --target br:${{ env.BICEP_TYPES_REGISTRY }}/testresources:latest" --force
+      - name: Publish Bicep Test Recipes
+        if: steps.skip-build.outputs.SKIP_BUILD != 'true'
+        run: |
           export PATH=$GITHUB_WORKSPACE/bin:$PATH
           which rad || { echo "cannot find rad"; exit 1; }
           rad bicep download
