Cherry pick 3 commits to release v0.51 branch (#10519)
# Description

Cherry Picking commits previously merged into main into release branch
release/0.51.

commits:
a0a2c5e72 Disable Gitea install and Flux tests (#10442)
6dbd2dac1 Disable Contour installation (Bitnami repo changes) (#10483)
df96264e3 (HEAD -> main, origin/main) Release Candidate v0.51.0-rc2
(#10507)

## Type of change
- This pull request is a minor refactor, code cleanup, test improvement,
or other maintenance task and doesn't change the functionality of Radius
(issue link optional).


## Contributor checklist
Please verify that the PR meets the following requirements, where
applicable:

<!--
This checklist uses "TaskRadio" comments to make certain options
mutually exclusive.
See:
https://github.com/mheap/require-checklist-action?tab=readme-ov-file#radio-groups
For details on how this works and why it's required.
-->

- An overview of proposed schema changes is included in a linked GitHub
issue.
    - [ ] Yes <!-- TaskRadio schema -->
    - [x] Not applicable <!-- TaskRadio schema -->
- A design document PR is created in the [design-notes
repository](https://github.com/radius-project/design-notes/), if new
APIs are being introduced.
    - [ ] Yes <!-- TaskRadio design-pr -->
    - [x] Not applicable <!-- TaskRadio design-pr -->
- The design document has been reviewed and approved by Radius
maintainers/approvers.
    - [ ] Yes <!-- TaskRadio design-review -->
    - [x] Not applicable <!-- TaskRadio design-review -->
- A PR for the [samples
repository](https://github.com/radius-project/samples) is created, if
existing samples are affected by the changes in this PR.
    - [ ] Yes <!-- TaskRadio samples-pr -->
    - [x] Not applicable <!-- TaskRadio samples-pr -->
- A PR for the [documentation
repository](https://github.com/radius-project/docs) is created, if the
changes in this PR affect the documentation or any user facing updates
are made.
    - [ ] Yes <!-- TaskRadio docs-pr -->
    - [x] Not applicable <!-- TaskRadio docs-pr -->
- A PR for the [recipes
repository](https://github.com/radius-project/recipes) is created, if
existing recipes are affected by the changes in this PR.
    - [ ] Yes <!-- TaskRadio recipes-pr -->
    - [x] Not applicable <!-- TaskRadio recipes-pr -->

---------

Signed-off-by: willdavsmith <willdavsmith@gmail.com>
Signed-off-by: lakshmimsft <ljavadekar@microsoft.com>
Co-authored-by: Will Smith <willdavsmith@gmail.com>

diff --git a/.github/workflows/long-running-azure.yaml b/.github/workflows/long-running-azure.yaml
--- a/.github/workflows/long-running-azure.yaml
+++ b/.github/workflows/long-running-azure.yaml
@@ -554,27 +554,27 @@ jobs:
           echo ":x: Failed to install Radius for functional test." >> $GITHUB_STEP_SUMMARY
       - name: Install Flux CLI and Source Controller
         uses: ./.github/actions/install-flux
-      - name: Install Gitea
-        id: install-gitea
-        uses: ./.github/actions/install-gitea
-        env:
-          GITEA_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
-        with:
-          gitea-username: ${{ env.GITEA_USERNAME }}
-          gitea-email: ${{ env.GITEA_EMAIL }}
-          gitea-access-token-name: ${{ env.GITEA_ACCESS_TOKEN_NAME }}
-      - name: Port-forward to Gitea
-        run: |
-          # Start port forwarding in the background
-          kubectl port-forward -n gitea svc/gitea-http 30080:3000 &
+      # - name: Install Gitea
+      #   id: install-gitea
+      #   uses: ./.github/actions/install-gitea
+      #   env:
+      #     GITEA_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
+      #   with:
+      #     gitea-username: ${{ env.GITEA_USERNAME }}
+      #     gitea-email: ${{ env.GITEA_EMAIL }}
+      #     gitea-access-token-name: ${{ env.GITEA_ACCESS_TOKEN_NAME }}
+      # - name: Port-forward to Gitea
+      #   run: |
+      #     # Start port forwarding in the background
+      #     kubectl port-forward -n gitea svc/gitea-http 30080:3000 &
           
-          # Wait for port forwarding to be established
-          sleep 5
+      #     # Wait for port forwarding to be established
+      #     sleep 5
           
-          # Test the connection to ensure port forwarding is working
-          curl -s http://localhost:30080 > /dev/null || (echo "Port forwarding failed" && exit 1)
+      #     # Test the connection to ensure port forwarding is working
+      #     curl -s http://localhost:30080 > /dev/null || (echo "Port forwarding failed" && exit 1)
           
-          echo "Port forwarding established successfully"
+      #     echo "Port forwarding established successfully"
       - name: Publish Terraform test recipes
         run: |
           make publish-test-terraform-recipes
@@ -621,7 +621,7 @@ jobs:
           BICEP_RECIPE_REGISTRY: ${{ env.BICEP_RECIPE_REGISTRY }}
           BICEP_RECIPE_TAG_VERSION: ${{ env.BICEP_RECIPE_TAG_VERSION }}
           GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
-          GITEA_ACCESS_TOKEN: ${{ steps.install-gitea.outputs.gitea-access-token }}
+          # GITEA_ACCESS_TOKEN: ${{ steps.install-gitea.outputs.gitea-access-token }}
       - name: Collect Pod details
         if: always()
         run: |
